import { createFileRoute } from "@tanstack/react-router";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * Service Worker Proxy Route.
 * TanStack Start / Nitro might not expose the root /sw.js generated by vite-plugin-pwa
 * if it's placed outside the public directory during build or if the router intercepts it.
 * 
 * This route ensures that /sw.js is ALWAYS available and served with the correct Content-Type,
 * even if the environment treats it as a dynamic route.
 */
export const Route = createFileRoute("/sw.js")({
  server: {
    handlers: {
      GET: async () => {
        // Paths to check based on typical TanStack Start / Nitro build outputs
        const paths = [
          join(process.cwd(), "public", "sw.js"),
          join(process.cwd(), "dist", "client", "sw.js"),
          join(process.cwd(), "dist", "sw.js"),
          join(process.cwd(), ".output", "public", "sw.js"),
          // Fallback for development if needed, though vite handles it there
          join(process.cwd(), "sw.js"),
        ];

        for (const p of paths) {
          if (existsSync(p)) {
            try {
              const content = readFileSync(p);
              return new Response(content, {
                headers: {
                  "Content-Type": "application/javascript; charset=utf-8",
                  "Cache-Control": "public, max-age=0, must-revalidate",
                  "Service-Worker-Allowed": "/",
                },
              });
            } catch (err) {
              console.error(`[sw-proxy] Error reading ${p}:`, err);
            }
          }
        }

        console.error("[sw-proxy] sw.js not found in searched paths:", paths);
        return new Response("Service Worker not found", { status: 404 });
      },
    },
  },
});
