-- 0006_triggers.sql — SKELETON
-- Extrair de pg_trigger.
-- Recriar em auth.users:
-- CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
