import { createFileRoute } from "@tanstack/react-router";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * Service Worker Proxy Route.
 * TanStack Start / Nitro might not expose the root /sw.js generated by vite-plugin-pwa
 * if it's placed outside the public directory during build or if the router intercepts it.
 */
export const Route = createFileRoute("/api/public/sw/js")({
  server: {
    handlers: {
      GET: async () => {
        const paths = [
          join(process.cwd(), "dist", "sw.js"),
          join(process.cwd(), "public", "sw.js"),
          join(process.cwd(), "dist", "client", "sw.js"),
          join(process.cwd(), ".output", "public", "sw.js"),
          join(process.cwd(), "sw.js"),
        ];

        for (const p of paths) {
          if (existsSync(p)) {
            try {
              const content = readFileSync(p);
              return new Response(content, {
                headers: {
                  "Content-Type": "application/javascript; charset=utf-8",
                  "Cache-Control": "public, max-age=0, must-revalidate",
                  "Service-Worker-Allowed": "/",
                  "X-SW-Path": p,
                },
              });
            } catch (err) {
              // noop
            }
          }
        }

        return new Response("Service Worker not found", { status: 404 });
      },
    },
  },
});
