/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuporteMeusRouteImport } from './routes/suporte.meus'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthNovaSenhaRouteImport } from './routes/auth.nova-senha'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SuporteSlugIndexRouteImport } from './routes/suporte.$slug.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SuporteChamadoIdRouteImport } from './routes/suporte.chamado.$id'
import { Route as SuporteSlugNovoRouteImport } from './routes/suporte.$slug.novo'
import { Route as AuthenticatedAppSuporteRouteImport } from './routes/_authenticated/app.suporte'
import { Route as AuthenticatedAppQrcodesRouteImport } from './routes/_authenticated/app.qrcodes'
import { Route as AuthenticatedAppKbRouteImport } from './routes/_authenticated/app.kb'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/app.equipe'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppCarimbarRouteImport } from './routes/_authenticated/app.carimbar'
import { Route as AuthenticatedAppCampanhasRouteImport } from './routes/_authenticated/app.campanhas'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/admin.assinaturas'
import { Route as AuthenticatedAdminAlertasRouteImport } from './routes/_authenticated/admin.alertas'
import { Route as SuporteSlugKbArticleRouteImport } from './routes/suporte.$slug.kb.$article'
import { Route as ApiPublicHooksProcessEmailQueueRouteImport } from './routes/api/public/hooks/process-email-queue'
import { Route as AuthenticatedAdminEmpresaIdRouteImport } from './routes/_authenticated/admin.empresa.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteMeusRoute = SuporteMeusRouteImport.update({
  id: '/suporte/meus',
  path: '/suporte/meus',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNovaSenhaRoute = AuthNovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SuporteSlugIndexRoute = SuporteSlugIndexRouteImport.update({
  id: '/suporte/$slug/',
  path: '/suporte/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SuporteChamadoIdRoute = SuporteChamadoIdRouteImport.update({
  id: '/suporte/chamado/$id',
  path: '/suporte/chamado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteSlugNovoRoute = SuporteSlugNovoRouteImport.update({
  id: '/suporte/$slug/novo',
  path: '/suporte/$slug/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSuporteRoute = AuthenticatedAppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppQrcodesRoute = AuthenticatedAppQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppKbRoute = AuthenticatedAppKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCarimbarRoute =
  AuthenticatedAppCarimbarRouteImport.update({
    id: '/carimbar',
    path: '/carimbar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasRoute =
  AuthenticatedAppCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlertasRoute =
  AuthenticatedAdminAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const SuporteSlugKbArticleRoute = SuporteSlugKbArticleRouteImport.update({
  id: '/suporte/$slug/kb/$article',
  path: '/suporte/$slug/kb/$article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessEmailQueueRoute =
  ApiPublicHooksProcessEmailQueueRouteImport.update({
    id: '/api/public/hooks/process-email-queue',
    path: '/api/public/hooks/process-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEmpresaIdRoute =
  AuthenticatedAdminEmpresaIdRouteImport.update({
    id: '/empresa/$id',
    path: '/empresa/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/kb': typeof AuthenticatedAppKbRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/suporte/$slug/': typeof SuporteSlugIndexRoute
  '/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/kb': typeof AuthenticatedAppKbRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/suporte/$slug': typeof SuporteSlugIndexRoute
  '/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/_authenticated/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/_authenticated/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/_authenticated/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/app/kb': typeof AuthenticatedAppKbRoute
  '/_authenticated/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/_authenticated/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/suporte/$slug/': typeof SuporteSlugIndexRoute
  '/_authenticated/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/app'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/suporte/meus'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/config'
    | '/admin/emails'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/equipe'
    | '/app/kb'
    | '/app/qrcodes'
    | '/app/suporte'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/admin/'
    | '/app/'
    | '/suporte/$slug/'
    | '/admin/empresa/$id'
    | '/api/public/hooks/process-email-queue'
    | '/suporte/$slug/kb/$article'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/suporte/meus'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/config'
    | '/admin/emails'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/equipe'
    | '/app/kb'
    | '/app/qrcodes'
    | '/app/suporte'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/admin'
    | '/app'
    | '/suporte/$slug'
    | '/admin/empresa/$id'
    | '/api/public/hooks/process-email-queue'
    | '/suporte/$slug/kb/$article'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/suporte/meus'
    | '/_authenticated/admin/alertas'
    | '/_authenticated/admin/assinaturas'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/app/campanhas'
    | '/_authenticated/app/carimbar'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/equipe'
    | '/_authenticated/app/kb'
    | '/_authenticated/app/qrcodes'
    | '/_authenticated/app/suporte'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/suporte/$slug/'
    | '/_authenticated/admin/empresa/$id'
    | '/api/public/hooks/process-email-queue'
    | '/suporte/$slug/kb/$article'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  CTokenRoute: typeof CTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LSlugRoute: typeof LSlugRoute
  SuporteMeusRoute: typeof SuporteMeusRoute
  SuporteSlugNovoRoute: typeof SuporteSlugNovoRoute
  SuporteChamadoIdRoute: typeof SuporteChamadoIdRoute
  SuporteSlugIndexRoute: typeof SuporteSlugIndexRoute
  ApiPublicHooksProcessEmailQueueRoute: typeof ApiPublicHooksProcessEmailQueueRoute
  SuporteSlugKbArticleRoute: typeof SuporteSlugKbArticleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/meus': {
      id: '/suporte/meus'
      path: '/suporte/meus'
      fullPath: '/suporte/meus'
      preLoaderRoute: typeof SuporteMeusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/nova-senha': {
      id: '/auth/nova-senha'
      path: '/nova-senha'
      fullPath: '/auth/nova-senha'
      preLoaderRoute: typeof AuthNovaSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/suporte/$slug/': {
      id: '/suporte/$slug/'
      path: '/suporte/$slug'
      fullPath: '/suporte/$slug/'
      preLoaderRoute: typeof SuporteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/suporte/chamado/$id': {
      id: '/suporte/chamado/$id'
      path: '/suporte/chamado/$id'
      fullPath: '/suporte/chamado/$id'
      preLoaderRoute: typeof SuporteChamadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/$slug/novo': {
      id: '/suporte/$slug/novo'
      path: '/suporte/$slug/novo'
      fullPath: '/suporte/$slug/novo'
      preLoaderRoute: typeof SuporteSlugNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/suporte': {
      id: '/_authenticated/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AuthenticatedAppSuporteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/qrcodes': {
      id: '/_authenticated/app/qrcodes'
      path: '/qrcodes'
      fullPath: '/app/qrcodes'
      preLoaderRoute: typeof AuthenticatedAppQrcodesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/kb': {
      id: '/_authenticated/app/kb'
      path: '/kb'
      fullPath: '/app/kb'
      preLoaderRoute: typeof AuthenticatedAppKbRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/equipe': {
      id: '/_authenticated/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/carimbar': {
      id: '/_authenticated/app/carimbar'
      path: '/carimbar'
      fullPath: '/app/carimbar'
      preLoaderRoute: typeof AuthenticatedAppCarimbarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas': {
      id: '/_authenticated/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AuthenticatedAppCampanhasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinaturas': {
      id: '/_authenticated/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alertas': {
      id: '/_authenticated/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AuthenticatedAdminAlertasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/suporte/$slug/kb/$article': {
      id: '/suporte/$slug/kb/$article'
      path: '/suporte/$slug/kb/$article'
      fullPath: '/suporte/$slug/kb/$article'
      preLoaderRoute: typeof SuporteSlugKbArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-email-queue': {
      id: '/api/public/hooks/process-email-queue'
      path: '/api/public/hooks/process-email-queue'
      fullPath: '/api/public/hooks/process-email-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/empresa/$id': {
      id: '/_authenticated/admin/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/admin/empresa/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlertasRoute: typeof AuthenticatedAdminAlertasRoute
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmpresaIdRoute: typeof AuthenticatedAdminEmpresaIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlertasRoute: AuthenticatedAdminAlertasRoute,
  AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEmpresaIdRoute: AuthenticatedAdminEmpresaIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCampanhasRoute: typeof AuthenticatedAppCampanhasRoute
  AuthenticatedAppCarimbarRoute: typeof AuthenticatedAppCarimbarRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppKbRoute: typeof AuthenticatedAppKbRoute
  AuthenticatedAppQrcodesRoute: typeof AuthenticatedAppQrcodesRoute
  AuthenticatedAppSuporteRoute: typeof AuthenticatedAppSuporteRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCampanhasRoute: AuthenticatedAppCampanhasRoute,
  AuthenticatedAppCarimbarRoute: AuthenticatedAppCarimbarRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppKbRoute: AuthenticatedAppKbRoute,
  AuthenticatedAppQrcodesRoute: AuthenticatedAppQrcodesRoute,
  AuthenticatedAppSuporteRoute: AuthenticatedAppSuporteRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthNovaSenhaRoute: typeof AuthNovaSenhaRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNovaSenhaRoute: AuthNovaSenhaRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  CTokenRoute: CTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  LSlugRoute: LSlugRoute,
  SuporteMeusRoute: SuporteMeusRoute,
  SuporteSlugNovoRoute: SuporteSlugNovoRoute,
  SuporteChamadoIdRoute: SuporteChamadoIdRoute,
  SuporteSlugIndexRoute: SuporteSlugIndexRoute,
  ApiPublicHooksProcessEmailQueueRoute: ApiPublicHooksProcessEmailQueueRoute,
  SuporteSlugKbArticleRoute: SuporteSlugKbArticleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
