/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PreviewDockRouteImport } from './routes/preview-dock'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaIndexRouteImport } from './routes/ajuda.index'
import { Route as SuporteMeusRouteImport } from './routes/suporte.meus'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AvaliarSlugRouteImport } from './routes/avaliar.$slug'
import { Route as AvaliacoesSlugRouteImport } from './routes/avaliacoes.$slug'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthNovaSenhaRouteImport } from './routes/auth.nova-senha'
import { Route as AuthenticatedLgpdRouteImport } from './routes/_authenticated/lgpd'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SuporteSlugIndexRouteImport } from './routes/suporte.$slug.index'
import { Route as AjudaCategoryIndexRouteImport } from './routes/ajuda.$category.index'
import { Route as AuthenticatedSuporteIndexRouteImport } from './routes/_authenticated/suporte.index'
import { Route as AuthenticatedCarteiraIndexRouteImport } from './routes/_authenticated/carteira.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SuporteChamadoIdRouteImport } from './routes/suporte.chamado.$id'
import { Route as SuporteSlugNovoRouteImport } from './routes/suporte.$slug.novo'
import { Route as AjudaCategoryArticleRouteImport } from './routes/ajuda.$category.$article'
import { Route as AuthenticatedCarteiraRecompensasRouteImport } from './routes/_authenticated/carteira.recompensas'
import { Route as AuthenticatedCarteiraPremiosRouteImport } from './routes/_authenticated/carteira.premios'
import { Route as AuthenticatedCarteiraPerfilRouteImport } from './routes/_authenticated/carteira.perfil'
import { Route as AuthenticatedCarteiraMensagensRouteImport } from './routes/_authenticated/carteira.mensagens'
import { Route as AuthenticatedCarteiraHistoricoRouteImport } from './routes/_authenticated/carteira.historico'
import { Route as AuthenticatedCarteiraDescobrirRouteImport } from './routes/_authenticated/carteira.descobrir'
import { Route as AuthenticatedCarteiraCartoesRouteImport } from './routes/_authenticated/carteira.cartoes'
import { Route as AuthenticatedCarteiraSlugRouteImport } from './routes/_authenticated/carteira.$slug'
import { Route as AuthenticatedAppSuporteRouteImport } from './routes/_authenticated/app.suporte'
import { Route as AuthenticatedAppRetencaoRouteImport } from './routes/_authenticated/app.retencao'
import { Route as AuthenticatedAppQrcodesRouteImport } from './routes/_authenticated/app.qrcodes'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppPagamentosRouteImport } from './routes/_authenticated/app.pagamentos'
import { Route as AuthenticatedAppNotificacoesRouteImport } from './routes/_authenticated/app.notificacoes'
import { Route as AuthenticatedAppMensagensRouteImport } from './routes/_authenticated/app.mensagens'
import { Route as AuthenticatedAppKbRouteImport } from './routes/_authenticated/app.kb'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/app.equipe'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppCarimbarRouteImport } from './routes/_authenticated/app.carimbar'
import { Route as AuthenticatedAppCampanhasRouteImport } from './routes/_authenticated/app.campanhas'
import { Route as AuthenticatedAppAvaliacoesRouteImport } from './routes/_authenticated/app.avaliacoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminEmailTemplatesRouteImport } from './routes/_authenticated/admin.email-templates'
import { Route as AuthenticatedAdminEmailFilaRouteImport } from './routes/_authenticated/admin.email-fila'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminAvaliacoesRouteImport } from './routes/_authenticated/admin.avaliacoes'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/admin.assinaturas'
import { Route as AuthenticatedAdminAlertasRouteImport } from './routes/_authenticated/admin.alertas'
import { Route as AuthenticatedAdminAjudaRouteImport } from './routes/_authenticated/admin.ajuda'
import { Route as AuthenticatedAppPlanosIndexRouteImport } from './routes/_authenticated/app.planos.index'
import { Route as AuthenticatedAdminSuporteIndexRouteImport } from './routes/_authenticated/admin.suporte.index'
import { Route as AuthenticatedAdminPlanosIndexRouteImport } from './routes/_authenticated/admin.planos.index'
import { Route as SuporteSlugKbArticleRouteImport } from './routes/suporte.$slug.kb.$article'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'
import { Route as ApiPublicMercadopagoPublicKeyRouteImport } from './routes/api/public/mercadopago/public-key'
import { Route as ApiPublicHooksProcessEmailQueueRouteImport } from './routes/api/public/hooks/process-email-queue'
import { Route as ApiPublicHooksMercadopagoRetryRouteImport } from './routes/api/public/hooks/mercadopago-retry'
import { Route as ApiPublicCronReengagementRouteImport } from './routes/api/public/cron/reengagement'
import { Route as ApiPublicCronBirthdayRouteImport } from './routes/api/public/cron/birthday'
import { Route as AuthenticatedSuporteTicketIdRouteImport } from './routes/_authenticated/suporte.ticket.$id'
import { Route as AuthenticatedAdminSuporteIdRouteImport } from './routes/_authenticated/admin.suporte.$id'
import { Route as AuthenticatedAdminEmpresaIdRouteImport } from './routes/_authenticated/admin.empresa.$id'
import { Route as ApiPublicWalletAppleTokenRouteImport } from './routes/api/public/wallet.apple.$token'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDockRoute = PreviewDockRouteImport.update({
  id: '/preview-dock',
  path: '/preview-dock',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaIndexRoute = AjudaIndexRouteImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteMeusRoute = SuporteMeusRouteImport.update({
  id: '/suporte/meus',
  path: '/suporte/meus',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarSlugRoute = AvaliarSlugRouteImport.update({
  id: '/avaliar/$slug',
  path: '/avaliar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesSlugRoute = AvaliacoesSlugRouteImport.update({
  id: '/avaliacoes/$slug',
  path: '/avaliacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNovaSenhaRoute = AuthNovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedLgpdRoute = AuthenticatedLgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SuporteSlugIndexRoute = SuporteSlugIndexRouteImport.update({
  id: '/suporte/$slug/',
  path: '/suporte/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaCategoryIndexRoute = AjudaCategoryIndexRouteImport.update({
  id: '/ajuda/$category/',
  path: '/ajuda/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteIndexRoute =
  AuthenticatedSuporteIndexRouteImport.update({
    id: '/suporte/',
    path: '/suporte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarteiraIndexRoute =
  AuthenticatedCarteiraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SuporteChamadoIdRoute = SuporteChamadoIdRouteImport.update({
  id: '/suporte/chamado/$id',
  path: '/suporte/chamado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteSlugNovoRoute = SuporteSlugNovoRouteImport.update({
  id: '/suporte/$slug/novo',
  path: '/suporte/$slug/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaCategoryArticleRoute = AjudaCategoryArticleRouteImport.update({
  id: '/ajuda/$category/$article',
  path: '/ajuda/$category/$article',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRecompensasRoute =
  AuthenticatedCarteiraRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraPremiosRoute =
  AuthenticatedCarteiraPremiosRouteImport.update({
    id: '/premios',
    path: '/premios',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraPerfilRoute =
  AuthenticatedCarteiraPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraMensagensRoute =
  AuthenticatedCarteiraMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraHistoricoRoute =
  AuthenticatedCarteiraHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraDescobrirRoute =
  AuthenticatedCarteiraDescobrirRouteImport.update({
    id: '/descobrir',
    path: '/descobrir',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraCartoesRoute =
  AuthenticatedCarteiraCartoesRouteImport.update({
    id: '/cartoes',
    path: '/cartoes',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraSlugRoute =
  AuthenticatedCarteiraSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedAppSuporteRoute = AuthenticatedAppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRetencaoRoute =
  AuthenticatedAppRetencaoRouteImport.update({
    id: '/retencao',
    path: '/retencao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQrcodesRoute = AuthenticatedAppQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPagamentosRoute =
  AuthenticatedAppPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificacoesRoute =
  AuthenticatedAppNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMensagensRoute =
  AuthenticatedAppMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKbRoute = AuthenticatedAppKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCarimbarRoute =
  AuthenticatedAppCarimbarRouteImport.update({
    id: '/carimbar',
    path: '/carimbar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasRoute =
  AuthenticatedAppCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAvaliacoesRoute =
  AuthenticatedAppAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesRoute =
  AuthenticatedAdminEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailFilaRoute =
  AuthenticatedAdminEmailFilaRouteImport.update({
    id: '/email-fila',
    path: '/email-fila',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvaliacoesRoute =
  AuthenticatedAdminAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlertasRoute =
  AuthenticatedAdminAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjudaRoute = AuthenticatedAdminAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppPlanosIndexRoute =
  AuthenticatedAppPlanosIndexRouteImport.update({
    id: '/planos/',
    path: '/planos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminSuporteIndexRoute =
  AuthenticatedAdminSuporteIndexRouteImport.update({
    id: '/suporte/',
    path: '/suporte/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlanosIndexRoute =
  AuthenticatedAdminPlanosIndexRouteImport.update({
    id: '/planos/',
    path: '/planos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const SuporteSlugKbArticleRoute = SuporteSlugKbArticleRouteImport.update({
  id: '/suporte/$slug/kb/$article',
  path: '/suporte/$slug/kb/$article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoPublicKeyRoute =
  ApiPublicMercadopagoPublicKeyRouteImport.update({
    id: '/api/public/mercadopago/public-key',
    path: '/api/public/mercadopago/public-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessEmailQueueRoute =
  ApiPublicHooksProcessEmailQueueRouteImport.update({
    id: '/api/public/hooks/process-email-queue',
    path: '/api/public/hooks/process-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMercadopagoRetryRoute =
  ApiPublicHooksMercadopagoRetryRouteImport.update({
    id: '/api/public/hooks/mercadopago-retry',
    path: '/api/public/hooks/mercadopago-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReengagementRoute =
  ApiPublicCronReengagementRouteImport.update({
    id: '/api/public/cron/reengagement',
    path: '/api/public/cron/reengagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBirthdayRoute = ApiPublicCronBirthdayRouteImport.update({
  id: '/api/public/cron/birthday',
  path: '/api/public/cron/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteTicketIdRoute =
  AuthenticatedSuporteTicketIdRouteImport.update({
    id: '/suporte/ticket/$id',
    path: '/suporte/ticket/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSuporteIdRoute =
  AuthenticatedAdminSuporteIdRouteImport.update({
    id: '/suporte/$id',
    path: '/suporte/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresaIdRoute =
  AuthenticatedAdminEmpresaIdRouteImport.update({
    id: '/empresa/$id',
    path: '/empresa/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWalletAppleTokenRoute =
  ApiPublicWalletAppleTokenRouteImport.update({
    id: '/api/public/wallet/apple/$token',
    path: '/api/public/wallet/apple/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/preview-dock': typeof PreviewDockRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/lgpd': typeof AuthenticatedLgpdRoute
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/avaliacoes/$slug': typeof AvaliacoesSlugRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$code': typeof RCodeRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/email-fila': typeof AuthenticatedAdminEmailFilaRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/kb': typeof AuthenticatedAppKbRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app/retencao': typeof AuthenticatedAppRetencaoRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/carteira/$slug': typeof AuthenticatedCarteiraSlugRoute
  '/carteira/cartoes': typeof AuthenticatedCarteiraCartoesRoute
  '/carteira/descobrir': typeof AuthenticatedCarteiraDescobrirRoute
  '/carteira/historico': typeof AuthenticatedCarteiraHistoricoRoute
  '/carteira/mensagens': typeof AuthenticatedCarteiraMensagensRoute
  '/carteira/perfil': typeof AuthenticatedCarteiraPerfilRoute
  '/carteira/premios': typeof AuthenticatedCarteiraPremiosRoute
  '/carteira/recompensas': typeof AuthenticatedCarteiraRecompensasRoute
  '/ajuda/$category/$article': typeof AjudaCategoryArticleRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/suporte/': typeof AuthenticatedSuporteIndexRoute
  '/ajuda/$category/': typeof AjudaCategoryIndexRoute
  '/suporte/$slug/': typeof SuporteSlugIndexRoute
  '/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/admin/suporte/$id': typeof AuthenticatedAdminSuporteIdRoute
  '/suporte/ticket/$id': typeof AuthenticatedSuporteTicketIdRoute
  '/api/public/cron/birthday': typeof ApiPublicCronBirthdayRoute
  '/api/public/cron/reengagement': typeof ApiPublicCronReengagementRoute
  '/api/public/hooks/mercadopago-retry': typeof ApiPublicHooksMercadopagoRetryRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/mercadopago/public-key': typeof ApiPublicMercadopagoPublicKeyRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
  '/admin/planos/': typeof AuthenticatedAdminPlanosIndexRoute
  '/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
  '/app/planos/': typeof AuthenticatedAppPlanosIndexRoute
  '/api/public/wallet/apple/$token': typeof ApiPublicWalletAppleTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/preview-dock': typeof PreviewDockRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/lgpd': typeof AuthenticatedLgpdRoute
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/avaliacoes/$slug': typeof AvaliacoesSlugRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$code': typeof RCodeRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/ajuda': typeof AjudaIndexRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/email-fila': typeof AuthenticatedAdminEmailFilaRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/kb': typeof AuthenticatedAppKbRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app/retencao': typeof AuthenticatedAppRetencaoRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/carteira/$slug': typeof AuthenticatedCarteiraSlugRoute
  '/carteira/cartoes': typeof AuthenticatedCarteiraCartoesRoute
  '/carteira/descobrir': typeof AuthenticatedCarteiraDescobrirRoute
  '/carteira/historico': typeof AuthenticatedCarteiraHistoricoRoute
  '/carteira/mensagens': typeof AuthenticatedCarteiraMensagensRoute
  '/carteira/perfil': typeof AuthenticatedCarteiraPerfilRoute
  '/carteira/premios': typeof AuthenticatedCarteiraPremiosRoute
  '/carteira/recompensas': typeof AuthenticatedCarteiraRecompensasRoute
  '/ajuda/$category/$article': typeof AjudaCategoryArticleRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/carteira': typeof AuthenticatedCarteiraIndexRoute
  '/suporte': typeof AuthenticatedSuporteIndexRoute
  '/ajuda/$category': typeof AjudaCategoryIndexRoute
  '/suporte/$slug': typeof SuporteSlugIndexRoute
  '/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/admin/suporte/$id': typeof AuthenticatedAdminSuporteIdRoute
  '/suporte/ticket/$id': typeof AuthenticatedSuporteTicketIdRoute
  '/api/public/cron/birthday': typeof ApiPublicCronBirthdayRoute
  '/api/public/cron/reengagement': typeof ApiPublicCronReengagementRoute
  '/api/public/hooks/mercadopago-retry': typeof ApiPublicHooksMercadopagoRetryRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/mercadopago/public-key': typeof ApiPublicMercadopagoPublicKeyRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosIndexRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteIndexRoute
  '/app/planos': typeof AuthenticatedAppPlanosIndexRoute
  '/api/public/wallet/apple/$token': typeof ApiPublicWalletAppleTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/preview-dock': typeof PreviewDockRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/_authenticated/lgpd': typeof AuthenticatedLgpdRoute
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/avaliacoes/$slug': typeof AvaliacoesSlugRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/c/$token': typeof CTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$code': typeof RCodeRoute
  '/suporte/meus': typeof SuporteMeusRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/_authenticated/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/_authenticated/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/_authenticated/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/email-fila': typeof AuthenticatedAdminEmailFilaRoute
  '/_authenticated/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/_authenticated/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/_authenticated/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/app/kb': typeof AuthenticatedAppKbRoute
  '/_authenticated/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/_authenticated/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/_authenticated/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/_authenticated/app/retencao': typeof AuthenticatedAppRetencaoRoute
  '/_authenticated/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/_authenticated/carteira/$slug': typeof AuthenticatedCarteiraSlugRoute
  '/_authenticated/carteira/cartoes': typeof AuthenticatedCarteiraCartoesRoute
  '/_authenticated/carteira/descobrir': typeof AuthenticatedCarteiraDescobrirRoute
  '/_authenticated/carteira/historico': typeof AuthenticatedCarteiraHistoricoRoute
  '/_authenticated/carteira/mensagens': typeof AuthenticatedCarteiraMensagensRoute
  '/_authenticated/carteira/perfil': typeof AuthenticatedCarteiraPerfilRoute
  '/_authenticated/carteira/premios': typeof AuthenticatedCarteiraPremiosRoute
  '/_authenticated/carteira/recompensas': typeof AuthenticatedCarteiraRecompensasRoute
  '/ajuda/$category/$article': typeof AjudaCategoryArticleRoute
  '/suporte/$slug/novo': typeof SuporteSlugNovoRoute
  '/suporte/chamado/$id': typeof SuporteChamadoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/_authenticated/suporte/': typeof AuthenticatedSuporteIndexRoute
  '/ajuda/$category/': typeof AjudaCategoryIndexRoute
  '/suporte/$slug/': typeof SuporteSlugIndexRoute
  '/_authenticated/admin/empresa/$id': typeof AuthenticatedAdminEmpresaIdRoute
  '/_authenticated/admin/suporte/$id': typeof AuthenticatedAdminSuporteIdRoute
  '/_authenticated/suporte/ticket/$id': typeof AuthenticatedSuporteTicketIdRoute
  '/api/public/cron/birthday': typeof ApiPublicCronBirthdayRoute
  '/api/public/cron/reengagement': typeof ApiPublicCronReengagementRoute
  '/api/public/hooks/mercadopago-retry': typeof ApiPublicHooksMercadopagoRetryRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/mercadopago/public-key': typeof ApiPublicMercadopagoPublicKeyRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/suporte/$slug/kb/$article': typeof SuporteSlugKbArticleRoute
  '/_authenticated/admin/planos/': typeof AuthenticatedAdminPlanosIndexRoute
  '/_authenticated/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
  '/_authenticated/app/planos/': typeof AuthenticatedAppPlanosIndexRoute
  '/api/public/wallet/apple/$token': typeof ApiPublicWalletAppleTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/preview-dock'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/app'
    | '/carteira'
    | '/lgpd'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/avaliacoes/$slug'
    | '/avaliar/$slug'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/r/$code'
    | '/suporte/meus'
    | '/ajuda/'
    | '/admin/ajuda'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/avaliacoes'
    | '/admin/config'
    | '/admin/email-fila'
    | '/admin/email-templates'
    | '/admin/emails'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/usuarios'
    | '/app/avaliacoes'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/equipe'
    | '/app/kb'
    | '/app/mensagens'
    | '/app/notificacoes'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/qrcodes'
    | '/app/retencao'
    | '/app/suporte'
    | '/carteira/$slug'
    | '/carteira/cartoes'
    | '/carteira/descobrir'
    | '/carteira/historico'
    | '/carteira/mensagens'
    | '/carteira/perfil'
    | '/carteira/premios'
    | '/carteira/recompensas'
    | '/ajuda/$category/$article'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/admin/'
    | '/app/'
    | '/carteira/'
    | '/suporte/'
    | '/ajuda/$category/'
    | '/suporte/$slug/'
    | '/admin/empresa/$id'
    | '/admin/suporte/$id'
    | '/suporte/ticket/$id'
    | '/api/public/cron/birthday'
    | '/api/public/cron/reengagement'
    | '/api/public/hooks/mercadopago-retry'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/mercadopago/public-key'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/mercadopago'
    | '/suporte/$slug/kb/$article'
    | '/admin/planos/'
    | '/admin/suporte/'
    | '/app/planos/'
    | '/api/public/wallet/apple/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/preview-dock'
    | '/privacidade'
    | '/termos'
    | '/lgpd'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/avaliacoes/$slug'
    | '/avaliar/$slug'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/r/$code'
    | '/suporte/meus'
    | '/ajuda'
    | '/admin/ajuda'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/avaliacoes'
    | '/admin/config'
    | '/admin/email-fila'
    | '/admin/email-templates'
    | '/admin/emails'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/usuarios'
    | '/app/avaliacoes'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/equipe'
    | '/app/kb'
    | '/app/mensagens'
    | '/app/notificacoes'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/qrcodes'
    | '/app/retencao'
    | '/app/suporte'
    | '/carteira/$slug'
    | '/carteira/cartoes'
    | '/carteira/descobrir'
    | '/carteira/historico'
    | '/carteira/mensagens'
    | '/carteira/perfil'
    | '/carteira/premios'
    | '/carteira/recompensas'
    | '/ajuda/$category/$article'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/admin'
    | '/app'
    | '/carteira'
    | '/suporte'
    | '/ajuda/$category'
    | '/suporte/$slug'
    | '/admin/empresa/$id'
    | '/admin/suporte/$id'
    | '/suporte/ticket/$id'
    | '/api/public/cron/birthday'
    | '/api/public/cron/reengagement'
    | '/api/public/hooks/mercadopago-retry'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/mercadopago/public-key'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/mercadopago'
    | '/suporte/$slug/kb/$article'
    | '/admin/planos'
    | '/admin/suporte'
    | '/app/planos'
    | '/api/public/wallet/apple/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/preview-dock'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/carteira'
    | '/_authenticated/lgpd'
    | '/auth/nova-senha'
    | '/auth/recuperar'
    | '/avaliacoes/$slug'
    | '/avaliar/$slug'
    | '/c/$token'
    | '/invite/$token'
    | '/l/$slug'
    | '/r/$code'
    | '/suporte/meus'
    | '/ajuda/'
    | '/_authenticated/admin/ajuda'
    | '/_authenticated/admin/alertas'
    | '/_authenticated/admin/assinaturas'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/avaliacoes'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/email-fila'
    | '/_authenticated/admin/email-templates'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/app/avaliacoes'
    | '/_authenticated/app/campanhas'
    | '/_authenticated/app/carimbar'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/equipe'
    | '/_authenticated/app/kb'
    | '/_authenticated/app/mensagens'
    | '/_authenticated/app/notificacoes'
    | '/_authenticated/app/pagamentos'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/qrcodes'
    | '/_authenticated/app/retencao'
    | '/_authenticated/app/suporte'
    | '/_authenticated/carteira/$slug'
    | '/_authenticated/carteira/cartoes'
    | '/_authenticated/carteira/descobrir'
    | '/_authenticated/carteira/historico'
    | '/_authenticated/carteira/mensagens'
    | '/_authenticated/carteira/perfil'
    | '/_authenticated/carteira/premios'
    | '/_authenticated/carteira/recompensas'
    | '/ajuda/$category/$article'
    | '/suporte/$slug/novo'
    | '/suporte/chamado/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/carteira/'
    | '/_authenticated/suporte/'
    | '/ajuda/$category/'
    | '/suporte/$slug/'
    | '/_authenticated/admin/empresa/$id'
    | '/_authenticated/admin/suporte/$id'
    | '/_authenticated/suporte/ticket/$id'
    | '/api/public/cron/birthday'
    | '/api/public/cron/reengagement'
    | '/api/public/hooks/mercadopago-retry'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/mercadopago/public-key'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/mercadopago'
    | '/suporte/$slug/kb/$article'
    | '/_authenticated/admin/planos/'
    | '/_authenticated/admin/suporte/'
    | '/_authenticated/app/planos/'
    | '/api/public/wallet/apple/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrecosRoute: typeof PrecosRoute
  PreviewDockRoute: typeof PreviewDockRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AvaliacoesSlugRoute: typeof AvaliacoesSlugRoute
  AvaliarSlugRoute: typeof AvaliarSlugRoute
  CTokenRoute: typeof CTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LSlugRoute: typeof LSlugRoute
  RCodeRoute: typeof RCodeRoute
  SuporteMeusRoute: typeof SuporteMeusRoute
  AjudaIndexRoute: typeof AjudaIndexRoute
  AjudaCategoryArticleRoute: typeof AjudaCategoryArticleRoute
  SuporteSlugNovoRoute: typeof SuporteSlugNovoRoute
  SuporteChamadoIdRoute: typeof SuporteChamadoIdRoute
  AjudaCategoryIndexRoute: typeof AjudaCategoryIndexRoute
  SuporteSlugIndexRoute: typeof SuporteSlugIndexRoute
  ApiPublicCronBirthdayRoute: typeof ApiPublicCronBirthdayRoute
  ApiPublicCronReengagementRoute: typeof ApiPublicCronReengagementRoute
  ApiPublicHooksMercadopagoRetryRoute: typeof ApiPublicHooksMercadopagoRetryRoute
  ApiPublicHooksProcessEmailQueueRoute: typeof ApiPublicHooksProcessEmailQueueRoute
  ApiPublicMercadopagoPublicKeyRoute: typeof ApiPublicMercadopagoPublicKeyRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  SuporteSlugKbArticleRoute: typeof SuporteSlugKbArticleRoute
  ApiPublicWalletAppleTokenRoute: typeof ApiPublicWalletAppleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-dock': {
      id: '/preview-dock'
      path: '/preview-dock'
      fullPath: '/preview-dock'
      preLoaderRoute: typeof PreviewDockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/': {
      id: '/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda/'
      preLoaderRoute: typeof AjudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/meus': {
      id: '/suporte/meus'
      path: '/suporte/meus'
      fullPath: '/suporte/meus'
      preLoaderRoute: typeof SuporteMeusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar/$slug': {
      id: '/avaliar/$slug'
      path: '/avaliar/$slug'
      fullPath: '/avaliar/$slug'
      preLoaderRoute: typeof AvaliarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/$slug': {
      id: '/avaliacoes/$slug'
      path: '/avaliacoes/$slug'
      fullPath: '/avaliacoes/$slug'
      preLoaderRoute: typeof AvaliacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/nova-senha': {
      id: '/auth/nova-senha'
      path: '/nova-senha'
      fullPath: '/auth/nova-senha'
      preLoaderRoute: typeof AuthNovaSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/lgpd': {
      id: '/_authenticated/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof AuthenticatedLgpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/suporte/$slug/': {
      id: '/suporte/$slug/'
      path: '/suporte/$slug'
      fullPath: '/suporte/$slug/'
      preLoaderRoute: typeof SuporteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$category/': {
      id: '/ajuda/$category/'
      path: '/ajuda/$category'
      fullPath: '/ajuda/$category/'
      preLoaderRoute: typeof AjudaCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte/': {
      id: '/_authenticated/suporte/'
      path: '/suporte'
      fullPath: '/suporte/'
      preLoaderRoute: typeof AuthenticatedSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira/': {
      id: '/_authenticated/carteira/'
      path: '/'
      fullPath: '/carteira/'
      preLoaderRoute: typeof AuthenticatedCarteiraIndexRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/suporte/chamado/$id': {
      id: '/suporte/chamado/$id'
      path: '/suporte/chamado/$id'
      fullPath: '/suporte/chamado/$id'
      preLoaderRoute: typeof SuporteChamadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/$slug/novo': {
      id: '/suporte/$slug/novo'
      path: '/suporte/$slug/novo'
      fullPath: '/suporte/$slug/novo'
      preLoaderRoute: typeof SuporteSlugNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$category/$article': {
      id: '/ajuda/$category/$article'
      path: '/ajuda/$category/$article'
      fullPath: '/ajuda/$category/$article'
      preLoaderRoute: typeof AjudaCategoryArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira/recompensas': {
      id: '/_authenticated/carteira/recompensas'
      path: '/recompensas'
      fullPath: '/carteira/recompensas'
      preLoaderRoute: typeof AuthenticatedCarteiraRecompensasRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/premios': {
      id: '/_authenticated/carteira/premios'
      path: '/premios'
      fullPath: '/carteira/premios'
      preLoaderRoute: typeof AuthenticatedCarteiraPremiosRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/perfil': {
      id: '/_authenticated/carteira/perfil'
      path: '/perfil'
      fullPath: '/carteira/perfil'
      preLoaderRoute: typeof AuthenticatedCarteiraPerfilRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/mensagens': {
      id: '/_authenticated/carteira/mensagens'
      path: '/mensagens'
      fullPath: '/carteira/mensagens'
      preLoaderRoute: typeof AuthenticatedCarteiraMensagensRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/historico': {
      id: '/_authenticated/carteira/historico'
      path: '/historico'
      fullPath: '/carteira/historico'
      preLoaderRoute: typeof AuthenticatedCarteiraHistoricoRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/descobrir': {
      id: '/_authenticated/carteira/descobrir'
      path: '/descobrir'
      fullPath: '/carteira/descobrir'
      preLoaderRoute: typeof AuthenticatedCarteiraDescobrirRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/cartoes': {
      id: '/_authenticated/carteira/cartoes'
      path: '/cartoes'
      fullPath: '/carteira/cartoes'
      preLoaderRoute: typeof AuthenticatedCarteiraCartoesRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/$slug': {
      id: '/_authenticated/carteira/$slug'
      path: '/$slug'
      fullPath: '/carteira/$slug'
      preLoaderRoute: typeof AuthenticatedCarteiraSlugRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/app/suporte': {
      id: '/_authenticated/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AuthenticatedAppSuporteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/retencao': {
      id: '/_authenticated/app/retencao'
      path: '/retencao'
      fullPath: '/app/retencao'
      preLoaderRoute: typeof AuthenticatedAppRetencaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/qrcodes': {
      id: '/_authenticated/app/qrcodes'
      path: '/qrcodes'
      fullPath: '/app/qrcodes'
      preLoaderRoute: typeof AuthenticatedAppQrcodesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pagamentos': {
      id: '/_authenticated/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AuthenticatedAppPagamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notificacoes': {
      id: '/_authenticated/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mensagens': {
      id: '/_authenticated/app/mensagens'
      path: '/mensagens'
      fullPath: '/app/mensagens'
      preLoaderRoute: typeof AuthenticatedAppMensagensRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/kb': {
      id: '/_authenticated/app/kb'
      path: '/kb'
      fullPath: '/app/kb'
      preLoaderRoute: typeof AuthenticatedAppKbRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/equipe': {
      id: '/_authenticated/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/carimbar': {
      id: '/_authenticated/app/carimbar'
      path: '/carimbar'
      fullPath: '/app/carimbar'
      preLoaderRoute: typeof AuthenticatedAppCarimbarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas': {
      id: '/_authenticated/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AuthenticatedAppCampanhasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/avaliacoes': {
      id: '/_authenticated/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAppAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-templates': {
      id: '/_authenticated/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-fila': {
      id: '/_authenticated/admin/email-fila'
      path: '/email-fila'
      fullPath: '/admin/email-fila'
      preLoaderRoute: typeof AuthenticatedAdminEmailFilaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avaliacoes': {
      id: '/_authenticated/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinaturas': {
      id: '/_authenticated/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alertas': {
      id: '/_authenticated/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AuthenticatedAdminAlertasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajuda': {
      id: '/_authenticated/admin/ajuda'
      path: '/ajuda'
      fullPath: '/admin/ajuda'
      preLoaderRoute: typeof AuthenticatedAdminAjudaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/planos/': {
      id: '/_authenticated/app/planos/'
      path: '/planos'
      fullPath: '/app/planos/'
      preLoaderRoute: typeof AuthenticatedAppPlanosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/suporte/': {
      id: '/_authenticated/admin/suporte/'
      path: '/suporte'
      fullPath: '/admin/suporte/'
      preLoaderRoute: typeof AuthenticatedAdminSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/planos/': {
      id: '/_authenticated/admin/planos/'
      path: '/planos'
      fullPath: '/admin/planos/'
      preLoaderRoute: typeof AuthenticatedAdminPlanosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/suporte/$slug/kb/$article': {
      id: '/suporte/$slug/kb/$article'
      path: '/suporte/$slug/kb/$article'
      fullPath: '/suporte/$slug/kb/$article'
      preLoaderRoute: typeof SuporteSlugKbArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/public-key': {
      id: '/api/public/mercadopago/public-key'
      path: '/api/public/mercadopago/public-key'
      fullPath: '/api/public/mercadopago/public-key'
      preLoaderRoute: typeof ApiPublicMercadopagoPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-email-queue': {
      id: '/api/public/hooks/process-email-queue'
      path: '/api/public/hooks/process-email-queue'
      fullPath: '/api/public/hooks/process-email-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mercadopago-retry': {
      id: '/api/public/hooks/mercadopago-retry'
      path: '/api/public/hooks/mercadopago-retry'
      fullPath: '/api/public/hooks/mercadopago-retry'
      preLoaderRoute: typeof ApiPublicHooksMercadopagoRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reengagement': {
      id: '/api/public/cron/reengagement'
      path: '/api/public/cron/reengagement'
      fullPath: '/api/public/cron/reengagement'
      preLoaderRoute: typeof ApiPublicCronReengagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/birthday': {
      id: '/api/public/cron/birthday'
      path: '/api/public/cron/birthday'
      fullPath: '/api/public/cron/birthday'
      preLoaderRoute: typeof ApiPublicCronBirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte/ticket/$id': {
      id: '/_authenticated/suporte/ticket/$id'
      path: '/suporte/ticket/$id'
      fullPath: '/suporte/ticket/$id'
      preLoaderRoute: typeof AuthenticatedSuporteTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suporte/$id': {
      id: '/_authenticated/admin/suporte/$id'
      path: '/suporte/$id'
      fullPath: '/admin/suporte/$id'
      preLoaderRoute: typeof AuthenticatedAdminSuporteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresa/$id': {
      id: '/_authenticated/admin/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/admin/empresa/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/wallet/apple/$token': {
      id: '/api/public/wallet/apple/$token'
      path: '/api/public/wallet/apple/$token'
      fullPath: '/api/public/wallet/apple/$token'
      preLoaderRoute: typeof ApiPublicWalletAppleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAjudaRoute: typeof AuthenticatedAdminAjudaRoute
  AuthenticatedAdminAlertasRoute: typeof AuthenticatedAdminAlertasRoute
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminAvaliacoesRoute: typeof AuthenticatedAdminAvaliacoesRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminEmailFilaRoute: typeof AuthenticatedAdminEmailFilaRoute
  AuthenticatedAdminEmailTemplatesRoute: typeof AuthenticatedAdminEmailTemplatesRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmpresaIdRoute: typeof AuthenticatedAdminEmpresaIdRoute
  AuthenticatedAdminSuporteIdRoute: typeof AuthenticatedAdminSuporteIdRoute
  AuthenticatedAdminPlanosIndexRoute: typeof AuthenticatedAdminPlanosIndexRoute
  AuthenticatedAdminSuporteIndexRoute: typeof AuthenticatedAdminSuporteIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAjudaRoute: AuthenticatedAdminAjudaRoute,
  AuthenticatedAdminAlertasRoute: AuthenticatedAdminAlertasRoute,
  AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminAvaliacoesRoute: AuthenticatedAdminAvaliacoesRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminEmailFilaRoute: AuthenticatedAdminEmailFilaRoute,
  AuthenticatedAdminEmailTemplatesRoute: AuthenticatedAdminEmailTemplatesRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEmpresaIdRoute: AuthenticatedAdminEmpresaIdRoute,
  AuthenticatedAdminSuporteIdRoute: AuthenticatedAdminSuporteIdRoute,
  AuthenticatedAdminPlanosIndexRoute: AuthenticatedAdminPlanosIndexRoute,
  AuthenticatedAdminSuporteIndexRoute: AuthenticatedAdminSuporteIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAvaliacoesRoute: typeof AuthenticatedAppAvaliacoesRoute
  AuthenticatedAppCampanhasRoute: typeof AuthenticatedAppCampanhasRoute
  AuthenticatedAppCarimbarRoute: typeof AuthenticatedAppCarimbarRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppKbRoute: typeof AuthenticatedAppKbRoute
  AuthenticatedAppMensagensRoute: typeof AuthenticatedAppMensagensRoute
  AuthenticatedAppNotificacoesRoute: typeof AuthenticatedAppNotificacoesRoute
  AuthenticatedAppPagamentosRoute: typeof AuthenticatedAppPagamentosRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppQrcodesRoute: typeof AuthenticatedAppQrcodesRoute
  AuthenticatedAppRetencaoRoute: typeof AuthenticatedAppRetencaoRoute
  AuthenticatedAppSuporteRoute: typeof AuthenticatedAppSuporteRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPlanosIndexRoute: typeof AuthenticatedAppPlanosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAvaliacoesRoute: AuthenticatedAppAvaliacoesRoute,
  AuthenticatedAppCampanhasRoute: AuthenticatedAppCampanhasRoute,
  AuthenticatedAppCarimbarRoute: AuthenticatedAppCarimbarRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppKbRoute: AuthenticatedAppKbRoute,
  AuthenticatedAppMensagensRoute: AuthenticatedAppMensagensRoute,
  AuthenticatedAppNotificacoesRoute: AuthenticatedAppNotificacoesRoute,
  AuthenticatedAppPagamentosRoute: AuthenticatedAppPagamentosRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppQrcodesRoute: AuthenticatedAppQrcodesRoute,
  AuthenticatedAppRetencaoRoute: AuthenticatedAppRetencaoRoute,
  AuthenticatedAppSuporteRoute: AuthenticatedAppSuporteRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPlanosIndexRoute: AuthenticatedAppPlanosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedCarteiraRouteChildren {
  AuthenticatedCarteiraSlugRoute: typeof AuthenticatedCarteiraSlugRoute
  AuthenticatedCarteiraCartoesRoute: typeof AuthenticatedCarteiraCartoesRoute
  AuthenticatedCarteiraDescobrirRoute: typeof AuthenticatedCarteiraDescobrirRoute
  AuthenticatedCarteiraHistoricoRoute: typeof AuthenticatedCarteiraHistoricoRoute
  AuthenticatedCarteiraMensagensRoute: typeof AuthenticatedCarteiraMensagensRoute
  AuthenticatedCarteiraPerfilRoute: typeof AuthenticatedCarteiraPerfilRoute
  AuthenticatedCarteiraPremiosRoute: typeof AuthenticatedCarteiraPremiosRoute
  AuthenticatedCarteiraRecompensasRoute: typeof AuthenticatedCarteiraRecompensasRoute
  AuthenticatedCarteiraIndexRoute: typeof AuthenticatedCarteiraIndexRoute
}

const AuthenticatedCarteiraRouteChildren: AuthenticatedCarteiraRouteChildren = {
  AuthenticatedCarteiraSlugRoute: AuthenticatedCarteiraSlugRoute,
  AuthenticatedCarteiraCartoesRoute: AuthenticatedCarteiraCartoesRoute,
  AuthenticatedCarteiraDescobrirRoute: AuthenticatedCarteiraDescobrirRoute,
  AuthenticatedCarteiraHistoricoRoute: AuthenticatedCarteiraHistoricoRoute,
  AuthenticatedCarteiraMensagensRoute: AuthenticatedCarteiraMensagensRoute,
  AuthenticatedCarteiraPerfilRoute: AuthenticatedCarteiraPerfilRoute,
  AuthenticatedCarteiraPremiosRoute: AuthenticatedCarteiraPremiosRoute,
  AuthenticatedCarteiraRecompensasRoute: AuthenticatedCarteiraRecompensasRoute,
  AuthenticatedCarteiraIndexRoute: AuthenticatedCarteiraIndexRoute,
}

const AuthenticatedCarteiraRouteWithChildren =
  AuthenticatedCarteiraRoute._addFileChildren(
    AuthenticatedCarteiraRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRouteWithChildren
  AuthenticatedLgpdRoute: typeof AuthenticatedLgpdRoute
  AuthenticatedSuporteIndexRoute: typeof AuthenticatedSuporteIndexRoute
  AuthenticatedSuporteTicketIdRoute: typeof AuthenticatedSuporteTicketIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRouteWithChildren,
  AuthenticatedLgpdRoute: AuthenticatedLgpdRoute,
  AuthenticatedSuporteIndexRoute: AuthenticatedSuporteIndexRoute,
  AuthenticatedSuporteTicketIdRoute: AuthenticatedSuporteTicketIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthNovaSenhaRoute: typeof AuthNovaSenhaRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNovaSenhaRoute: AuthNovaSenhaRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrecosRoute: PrecosRoute,
  PreviewDockRoute: PreviewDockRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AvaliacoesSlugRoute: AvaliacoesSlugRoute,
  AvaliarSlugRoute: AvaliarSlugRoute,
  CTokenRoute: CTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  LSlugRoute: LSlugRoute,
  RCodeRoute: RCodeRoute,
  SuporteMeusRoute: SuporteMeusRoute,
  AjudaIndexRoute: AjudaIndexRoute,
  AjudaCategoryArticleRoute: AjudaCategoryArticleRoute,
  SuporteSlugNovoRoute: SuporteSlugNovoRoute,
  SuporteChamadoIdRoute: SuporteChamadoIdRoute,
  AjudaCategoryIndexRoute: AjudaCategoryIndexRoute,
  SuporteSlugIndexRoute: SuporteSlugIndexRoute,
  ApiPublicCronBirthdayRoute: ApiPublicCronBirthdayRoute,
  ApiPublicCronReengagementRoute: ApiPublicCronReengagementRoute,
  ApiPublicHooksMercadopagoRetryRoute: ApiPublicHooksMercadopagoRetryRoute,
  ApiPublicHooksProcessEmailQueueRoute: ApiPublicHooksProcessEmailQueueRoute,
  ApiPublicMercadopagoPublicKeyRoute: ApiPublicMercadopagoPublicKeyRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  SuporteSlugKbArticleRoute: SuporteSlugKbArticleRoute,
  ApiPublicWalletAppleTokenRoute: ApiPublicWalletAppleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
