/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppQrcodesRouteImport } from './routes/_authenticated/app.qrcodes'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/app.equipe'
import { Route as AuthenticatedAppConfigRouteImport } from './routes/_authenticated/app.config'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppCarimbarRouteImport } from './routes/_authenticated/app.carimbar'
import { Route as AuthenticatedAppCampanhasRouteImport } from './routes/_authenticated/app.campanhas'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppQrcodesRoute = AuthenticatedAppQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfigRoute = AuthenticatedAppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCarimbarRoute =
  AuthenticatedAppCarimbarRouteImport.update({
    id: '/carimbar',
    path: '/carimbar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasRoute =
  AuthenticatedAppCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/config': typeof AuthenticatedAppConfigRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/c/$token': typeof CTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/config': typeof AuthenticatedAppConfigRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/_authenticated/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/_authenticated/app/carimbar': typeof AuthenticatedAppCarimbarRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/config': typeof AuthenticatedAppConfigRoute
  '/_authenticated/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/app/qrcodes': typeof AuthenticatedAppQrcodesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/app'
    | '/c/$token'
    | '/l/$slug'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/config'
    | '/app/equipe'
    | '/app/qrcodes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/c/$token'
    | '/l/$slug'
    | '/app/campanhas'
    | '/app/carimbar'
    | '/app/clientes'
    | '/app/config'
    | '/app/equipe'
    | '/app/qrcodes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/app'
    | '/c/$token'
    | '/l/$slug'
    | '/_authenticated/app/campanhas'
    | '/_authenticated/app/carimbar'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/config'
    | '/_authenticated/app/equipe'
    | '/_authenticated/app/qrcodes'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  CTokenRoute: typeof CTokenRoute
  LSlugRoute: typeof LSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/qrcodes': {
      id: '/_authenticated/app/qrcodes'
      path: '/qrcodes'
      fullPath: '/app/qrcodes'
      preLoaderRoute: typeof AuthenticatedAppQrcodesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/equipe': {
      id: '/_authenticated/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/config': {
      id: '/_authenticated/app/config'
      path: '/config'
      fullPath: '/app/config'
      preLoaderRoute: typeof AuthenticatedAppConfigRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/carimbar': {
      id: '/_authenticated/app/carimbar'
      path: '/carimbar'
      fullPath: '/app/carimbar'
      preLoaderRoute: typeof AuthenticatedAppCarimbarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas': {
      id: '/_authenticated/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AuthenticatedAppCampanhasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCampanhasRoute: typeof AuthenticatedAppCampanhasRoute
  AuthenticatedAppCarimbarRoute: typeof AuthenticatedAppCarimbarRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppConfigRoute: typeof AuthenticatedAppConfigRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppQrcodesRoute: typeof AuthenticatedAppQrcodesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCampanhasRoute: AuthenticatedAppCampanhasRoute,
  AuthenticatedAppCarimbarRoute: AuthenticatedAppCarimbarRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppConfigRoute: AuthenticatedAppConfigRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppQrcodesRoute: AuthenticatedAppQrcodesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  CTokenRoute: CTokenRoute,
  LSlugRoute: LSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
